name: qlora
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - rust=1.64.0
  - pip
  - pip:
    #  see qlora requirements
    - bitsandbytes==0.39.0
    - transformers @ git+https://github.com/huggingface/transformers.git
    - peft @ git+https://github.com/huggingface/peft.git
    - accelerate @ git+https://github.com/huggingface/accelerate.git
    - einops==0.6.1
    - evaluate==0.4.0
    - scikit-learn==1.2.2
    - sentencepiece==0.1.99
    - wandb==0.15.3
    # oplatek debugging tools
    - ipdb
    - exp-notifier
